### PR TITLE
Add warning about std::process::exit

### PR DESCRIPTION
**Pull request by Licenser**
Add a warning about using `exit(_)` and include an example how to resolve the issue.

### CODE REVIEW

**Comment by dpc** [comment]
Doctests are failing in travis? Mind fixing it? :)

**Comment by Licenser** [comment]
Oh damn it, I didn't even noticed that, I ran them locally to check and it worked -.- of cause fixing it!

**Comment by Licenser** [comment]
Sorry about that, the doc for `exit(1)` did cause the doctest to `exit(1)`. Commented that line out to not prematurely exit the tests.

**Comment by dpc** [comment]
Awesome!

**Pull request merged**
