### PR TITLE
Update dependency and Fix warnings

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by dpc** [comment]
Thanks!

**Comment by koushiro** [comment]
@dpc, can you release a new version with this change ?

**Comment by koushiro** [comment]
> @dpc, can you release a new version with this change ?

@dpc  It would be nice of you to release a new version (v2.4.1) so that downstream users can get rid of crossbeam-channel 0.3 in their crate graph.

**Comment by dpc** [comment]
@koushiro Done.

**Pull request merged**
