### PR TITLE
Prepare release 2.7.0

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@dpc please review

Release 2.6.0 was missing in the changelog, but is present on crates.io: https://crates.io/crates/slog-async/versions

Could you release it to crates.io? I don't have the permissions to do it.

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
Invitation sent.

**Comment by njam** [comment]
It's probably good to also create a git tag for the new version.

Could you do it, or give me write permissions on the repo, so I can do it?

**Comment by njam** [comment]
thx, it's released: https://crates.io/crates/slog-async/2.7.0

**Pull request merged**
